spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}?serverTimezone=Asia/Seoul
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true         # hibernate가 DB에 날리는 모든 쿼리 표시
        format_sql: true       # sql format 설정
        use_sql_comments: true # 주석 표시
        highlight_sql: true    # ANSI SQL에 맞게 색 출력
        type: trace

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace # parameter 값을 표시